# Allow compute credits usage for collaborators and anything pushed to the
# master, staging, and trying branches. (So bors can use them.)
use_compute_credits: $CIRRUS_USER_COLLABORATOR == 'true' || $CIRRUS_BRANCH == 'master' || $CIRRUS_BRANCH == 'staging' || $CIRRUS_BRANCH == 'trying'

# This makes Click, a Bork dependency, behave itself.
env:
  LC_ALL: C.UTF-8
  LANG: C.UTF-8

Lint_task:
  container:
    image: python:3-slim
  install_script:
    - pip install . .[testing]
  script:
    - pylint --version
    - bork run lint

Test_task:
  container:
    matrix:
      - image: python:3.6-slim
      - image: python:3.7-slim
      - image: python:3.8-slim
  install_script:
    - pip install . .[testing]
  script:
    - python3 --version
    - bork run test

# If lla/version.py is modified on the master branch, make a release.
Release_task:
  only_if: "changesInclude('lla/version.py') && $BRANCH == 'master' && $CIRRUS_CRON == ''"
  depends_on:
    - Lint
    - Test
  env:
    TWINE_USERNAME: "__token__"
    TWINE_PASSWORD: ENCRYPTED[c2cb5f064dcab0eb2c980a77e94c6e617f18c56580847944b58fcad892dafc21b1cb3f76153a40cd0dccf2b03a92f9e7]
    # BORK_GITHUB_TOKEN: ENCRYPTED[...]
  container:
    image: python:3.8-slim
  install_script:
    - apt-get update
    - apt-get install -y git
    - pip3 install . .[testing]
  build_script:
    - bork clean
    - bork build
  test_script:
    - bork run test
  release_script:
    - bork release
